"""
AI_HUB_BIG_GENERATOR.py

Generates a large AI_HUB file with at least N lines (default 10000) by
repeating a base AI_HUB content block and inserting useful index and demo
routines. This avoids committing an enormous file directly and lets you
create the large file locally or in CI by running this script.

Usage:
  python AI_HUB_BIG_GENERATOR.py --output AI_HUB_10000_LINES.py --lines 10000

This will produce AI_HUB_10000_LINES.py in the current directory.
"""
from __future__ import annotations

import argparse
import textwrap
import sys
from typing import List

BASE_BLOCK = textwrap.dedent('''
# AI_HUB core block
# This block provides an index of modules and a few lightweight demo functions.
# It is safe to repeat; the resulting large file can be searched for the
# function names and used as a single-file aggregation of the AI code index.

MODULE_INDEX = {
    "ingestion": "TradingAI/ingest/pdf_image_ingest.py  (Ingestor: PDF text extraction, image OCR, chunking)",
    "embeddings": "TradingAI/ai/embeddings.py           (EmbeddingService: sentence-transformers / OpenAI fallback)",
    "vector_store": "TradingAI/memory/vector_store.py     (VectorStore: Chroma wrapper + filesystem fallback)",
    "transformer_memory": "TradingAI/ai/transformer_pipeline.py (TransformerPipeline with memory integration)",
    "phi_tokenizer": "TradingAI/ai/tokenizers.py          (PhiTokenizer, WordTokenizer, HFTokenizer)",
    "phi_embedding": "TradingAI/ai/phi_embedding.py      (PhiHashedEmbedding: learned hashed embedding)",
    "gnn": "TradingAI/ai/graph_network.py             (Simple GNN skeleton for spatio-temporal graphs)",
    "multi_brain": "TradingAI/ai/multi_brain.py         (Router and MultiBrainController)",
    "deep_learning": "TradingAI/ai/deep_learning.py     (LMWrapper: HF LM + fine-tune helpers)",
    "rl_agent": "TradingAI/ai/rl_agent.py               (PPOAgent: policy & value nets + utils)",
}


def print_index():
    print("AI MODULE INDEX (paths)")
    for k, v in MODULE_INDEX.items():
        print(f" - {k:20s} : {v}")


def hello_demonstration():
    print('Hello from AI_HUB core block. Search the repo paths above to inspect modules.')

# Small util function included in every block to demonstrate repeatability

def repeatable_checksum(tag: str) -> int:
    """Deterministic small checksum of a tag string (toy function)."""
    s = 0
    for ch in tag:
        s = (s * 31 + ord(ch)) % 1000003
    return s

''')

FILLER_LINE_TEMPLATE = "# filler line {idx} - keeps AI_HUB file large and searchable.\n"


def generate_large_file(output: str, min_lines: int = 10000, block: str = BASE_BLOCK) -> None:
    """Generate a large python file by writing the base block and repeating
    it with slight annotations until we reach min_lines."""
    lines_written = 0
    blocks_written = 0
    with open(output, 'w', encoding='utf-8') as fh:
        # header
        fh.write("\"\"\"\nLarge AI_HUB aggregated file generated by AI_HUB_BIG_GENERATOR.py\n" )
        fh.write("Contains repeated core blocks and filler comments to reach the requested line count.\n")
        fh.write("Generated for repository: AlenJohnyRich/Trading-Strategist\n")
        fh.write("\"\"\"\n\n")
        lines_written += 7

        # write the base block once
        fh.write(block)
        lines_written += block.count('\n')
        blocks_written += 1

        # now append repeated blocks with slight modifications
        idx = 0
        while lines_written < min_lines:
            idx += 1
            # Write a small header for this repetition
            header = f"\n# --- repeated block {idx} (checksum={repeatable_checksum(str(idx))}) ---\n"
            fh.write(header)
            lines_written += header.count('\n')

            # write the base block but annotate function names to be unique per block
            annotated_block = block.replace('print_index', f'print_index_block_{idx}').replace('hello_demonstration', f'hello_demonstration_block_{idx}')
            fh.write(annotated_block)
            lines_written += annotated_block.count('\n')
            blocks_written += 1

            # add filler lines to control the line count growth
            # write in chunks of 100 lines per iteration for speed
            for j in range(100):
                if lines_written >= min_lines:
                    break
                fh.write(FILLER_LINE_TEMPLATE.format(idx=(idx*100 + j)))
                lines_written += 1

        # final footer
        footer = f"\n# Generated {blocks_written} blocks, total lines approx {lines_written}.\n"
        fh.write(footer)
    print(f"Wrote {lines_written} lines to {output} (approx). Blocks: {blocks_written}.")


def main(argv: List[str] = None) -> int:
    parser = argparse.ArgumentParser(description='Generate large AI_HUB file (>= N lines)')
    parser.add_argument('--output', '-o', type=str, default='AI_HUB_10000_LINES.py', help='Output file path')
    parser.add_argument('--lines', '-n', type=int, default=10000, help='Minimum number of lines to generate')
    args = parser.parse_args(argv)

    print(f"Generating file {args.output} with at least {args.lines} lines...")
    generate_large_file(args.output, min_lines=args.lines)
    print('Done.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
